# Generated by Django 3.0.8 on 2020-07-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('django_comments_xtd', '0006_auto_20181204_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='comments_cms_integration_commentpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_comments_xtd.XtdComment')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
